### ISSUE TITLE
Segmentation fault in textextract

### ISSUE THREAD

**Issue by eribertomota** [jbj/magicrescue#2]
This is a copy from Debian bug #716387, available here[1].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=716387

-----
textextract crashes with exit status 139. We confirmed the crash by
re-running it in a fresh debian unstable installation.

The attachment contains a testcase (under ./crash) crashing the
program. It ensures that you can easily reproduce the bug. Additionally,
under ./crash_info/, we include more information about the crash such as
a core dump, the dmesg generated by the crash, and its output.

Regards,
The Mayhem Team (Alexandre Rebert, Thanassis Avgerinos, Sang Kil Cha, David Brumley, Manuel Egele)
Cylab, Carnegie Mellon University

[textextract-report.zip](https://github.com/jbj/magicrescue/files/2627027/textextract-report.zip)

-----

Regards,

Eriberto

**Comment by jbj** [comment]
Thanks for the report. Fixed in 7ae1f59d73347c2852369ad97d5e55e6284d5a2b.

**Comment by eribertomota** [comment]
Thanks a lot!

Do you intent to release a new version or should I create a patch for Debian?

Cheers,

Eriberto

**Comment by jbj** [comment]
I'm not planning to release a new version with just this fix. I don't think any user will trigger this bug by accident.

**Comment by eribertomota** [comment]
Thanks! Uploaded to Debian as patch.
