### ISSUE TITLE
tests/samples/elf should have a source code

### ISSUE THREAD

**Issue by eribertomota** [jbj/magicrescue#3]
Dear @jbj,

On Debian, the lintian system shows:

`E: magicrescue source: source-is-missing tests/samples/elf`

I know that is it a file for a trivial test only. However, is a good idea provide all source codes when distributing free/libre projects. Can you include a source code for elf? It will avoid a binary without a source inside of the operational systems.

Thanks in advance.

Cheers,

Eriberto

**Comment by jbj** [comment]
That's technically a valid point. I'm not going to address this myself, but contributions will be gratefully considered.

**Comment by eribertomota** [comment]
Thanks for your reply. After an inspect with command `strace`, confirmed by binary size comparison, I am sure that the source code is true.c (/bin/true) from coreutils-5.2.1, under GPL-2+.

I will send a push request. My question now is: do you want I change the source name to elf.c or should I keep true.c and rename elf to true?

**Comment by jbj** [comment]
I prefer the binary to still be named `elf`.

**Comment by eribertomota** [comment]
Great!

**Comment by eribertomota** [comment]
I sent a PR. I will be grateful if you release a new version to fix this issue in Debian and other OS.

**Comment by eribertomota** [comment]
Closed via #5
